### PR TITLE
Add logic

### PR DESCRIPTION
**Pull request by emmamendelsohn**
Addresses issue #8.  A couple notes:

- I made some minor adjustments to the values provided in `DataCleanupFields.xlsx` to ensure that values exactly match what is in `eidith`.  It's possible that I missed something, so it would be worthwhile to have a second set of eyes to make sure all the rules are properly enforced.
- Some of the new conditions create cases where there are values that are populated but not checked.  For example, in the `Animal` table, `AnimalUseProducedSold` is only checked for empty values if `DiseaseTransmissionInterfaces` includes animal production, wildlife restaurant, or market and value chain, yet `AnimalUseProducedSold` is sometimes populated at other interfaces (e.g., natural areas).  This may be okay--just want to raise the flag in case.

### CODE REVIEW

**Comment by noamross** [comment]
Thanks @emmamendelsohn! @tmorourk, can you comment on Emma's flag above?

**Comment by tmorourk** [comment]
Thanks @emmamendelsohn I will take a look.  The last bullet doesn't make sense to me (natural areas shouldn't have  a value in AnimalUseProducedSold)  but I'll double check.

**Comment by emmamendelsohn** [comment]
@tmorourk The example I referenced is in the Thailand `animal` table.  Looks like there are 35 cases of `AnimalUseProducedSold` = "food" when `DiseaseTransmissionInterfaces` = "natural areas".

Perhaps we need to incorporate a check to confirm that all values are empty when a condition is _not_ met?

**Comment by emmamendelsohn** [comment]
To provide another example of the issue raised in the second bullet: 

We have a condition where `DurationDays` in the `Event` table should only be checked when `DiseaseTransmissionInterfaces` is _not_ human hospital.  However, there are cases where `DurationDays` is populated when the `DiseaseTransmissionInterfaces` is human hospital (e.g., Bangladesh).

**Comment by tmorourk** [comment]
Hi Emma,
I was wrong about the AnimalUseProducedSold - this should have a value if the AnimalHumanInterfaces are:
hunted
for sale in restaurant
for sale in small market (< 5 vendors)
for sale in medium market (5-20 vendors)
for sale in large market (> 20 vendors) 
at abattoir/slaughterhouse
at temporary holding facility in value chain
in transit along the value chain
animal or animal product destined for consumption

Also, I was wrong about the DurationDays - it is collected for hospital events, so you can remove that rule.

So sorry for the extra work!!

**Comment by emmamendelsohn** [comment]
No worries @tmorourk -- easy fixes.  Thanks for looking into it!

**Comment by noamross** [comment]
OK, I've incorporated @tmorourk's comments and will merge these changes in.

**Pull request merged**
